"""empty message

Revision ID: b3590faf4eaf
Revises: becad6cdbeda
Create Date: 2026-06-19 12:10:03.009256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3590faf4eaf'
down_revision = 'becad6cdbeda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('feature', sa.String(), nullable=True),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('quota')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quota',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ord_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('feature', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('period', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('quota_pkey'))
    )
    op.drop_table('quotas')
    # ### end Alembic commands ###
