"""add quota to model

Revision ID: becad6cdbeda
Revises: 
Create Date: 2026-06-19 11:04:26.369911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'becad6cdbeda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quota',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ord_id', sa.UUID(), nullable=False),
    sa.Column('feature', sa.String(), nullable=True),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quota')
    # ### end Alembic commands ###
